# Generated by Django 5.1.1 on 2025-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0004_alter_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='specs',
            field=models.TextField(),
        ),
    ]
