# Generated by Django 5.1.1 on 2025-04-14 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0008_cart_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='purchased_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
