# Generated by Django 5.1.1 on 2025-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0011_cart_address_cart_order_status_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mob_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
